language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#빌드 전 권한 추가
before_install:
  - chmod +x gradlew

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

addons:
  sonarcloud:
    organization: "lehdqlsl"
    token:
      secure: ae08d2486e2eadb3e508830d898c56045a248775

after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./gradlew sonarqube

# 빌드 메일 알람
notification:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email:
    recipients:
      - ldb955@telefield.com

        travis encrypt ae08d2486e2eadb3e508830d898c56045a248775